package bg.restaurant.swing.db;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.DriverPropertyInfo;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.Locale;
import java.util.Properties;
import java.util.UUID;
import java.util.logging.Logger;

public final class Db {
    private static volatile boolean driverReady = false;

    private Db() {}

    public static Connection connect() throws SQLException {
        ensureDriverLoaded();
        // Prefer ./data when writable (development). Packaged installers often run under
        // install dirs (e.g. Program Files) where ./data fails — then use per-user folder.
        Path dbStem = resolveWorktimeDbStem();
        String dbPath = dbStem.toAbsolutePath().normalize().toString().replace("\\", "/");
        String url = "jdbc:h2:file:" + dbPath + ";MODE=PostgreSQL";
        return DriverManager.getConnection(url, "sa", "");
    }

    /** H2 stem path without extension (.mv.db is added by engine). */
    private static Path resolveWorktimeDbStem() throws SQLException {
        Path cwdData = Path.of("data").toAbsolutePath().normalize();
        if (isDirectoryWritableProbe(cwdData)) {
            return cwdData.resolve("worktime");
        }
        Path userDataDir = writableAppDataRoot().resolve("data");
        try {
            Files.createDirectories(userDataDir);
        } catch (IOException e) {
            throw new SQLException("Не може да се подготви директория за база: " + userDataDir, e);
        }
        if (!isDirectoryWritableProbe(userDataDir)) {
            throw new SQLException(
                    "Няма права за запис в " + userDataDir + ". Пробвай като локална инсталация без Program Files или изпълни с администратор.");
        }
        return userDataDir.resolve("worktime");
    }

    private static boolean isDirectoryWritableProbe(Path dir) {
        try {
            Files.createDirectories(dir);
            Path probe = dir.resolve(".wt_probe_" + UUID.randomUUID());
            Files.writeString(probe, "");
            Files.delete(probe);
            return true;
        } catch (Exception ignored) {
            return false;
        }
    }

    private static Path writableAppDataRoot() {
        String os = System.getProperty("os.name", "").toLowerCase(Locale.ROOT);
        if (os.contains("windows")) {
            String localApp = System.getenv("LOCALAPPDATA");
            if (localApp != null && !localApp.isBlank()) {
                return Path.of(localApp).resolve("WorkTimeBG");
            }
            return Path.of(System.getProperty("user.home")).resolve("AppData").resolve("Local").resolve("WorkTimeBG");
        }
        if (os.contains("mac")) {
            return Path.of(System.getProperty("user.home"), "Library", "Application Support", "WorkTimeBG");
        }
        return Path.of(System.getProperty("user.home")).resolve(".local").resolve("share").resolve("WorkTimeBG");
    }

    public static void init() throws SQLException {
        try (Connection c = connect(); Statement s = c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS employee (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(200) NOT NULL UNIQUE" +
                    ")");

            s.execute("CREATE TABLE IF NOT EXISTS shift (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "employee_id BIGINT NOT NULL, " +
                    "start_time TIMESTAMP NOT NULL, " +
                    "end_time TIMESTAMP NULL, " +
                    "CONSTRAINT fk_shift_employee FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE" +
                    ")");

            s.execute("CREATE INDEX IF NOT EXISTS idx_shift_employee ON shift(employee_id)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_shift_start ON shift(start_time)");

            s.execute("CREATE TABLE IF NOT EXISTS app_user (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "access_code VARCHAR(32) NOT NULL UNIQUE, " +
                    "is_admin BOOLEAN NOT NULL DEFAULT FALSE" +
                    ")");
            s.execute("ALTER TABLE app_user ADD COLUMN IF NOT EXISTS display_name VARCHAR(200)");
            s.execute("ALTER TABLE app_user ADD COLUMN IF NOT EXISTS employee_id BIGINT");

            s.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_app_user_code ON app_user(access_code)");

            // Ensure default admin user exists.
            try (PreparedStatement ps = c.prepareStatement(
                    "MERGE INTO app_user(access_code, is_admin, display_name, employee_id) KEY(access_code) VALUES (?, ?, ?, ?)")) {
                ps.setString(1, "9876");
                ps.setBoolean(2, true);
                ps.setString(3, "Админ");
                ps.setObject(4, null);
                ps.executeUpdate();
            }
        }
    }

    private static synchronized void ensureDriverLoaded() throws SQLException {
        if (driverReady) return;

        try {
            Class.forName("org.h2.Driver");
            driverReady = true;
            return;
        } catch (ClassNotFoundException ignored) {
            // fallback below
        }

        try {
            Path jarPath = Path.of("lib", "h2.jar").toAbsolutePath();
            if (!jarPath.toFile().exists()) {
                throw new SQLException("Липсва H2 библиотека: " + jarPath);
            }
            URL jarUrl = jarPath.toUri().toURL();
            URLClassLoader loader = new URLClassLoader(new URL[]{jarUrl}, Db.class.getClassLoader());
            Class<?> driverClass = Class.forName("org.h2.Driver", true, loader);
            Driver driver = (Driver) driverClass.getDeclaredConstructor().newInstance();
            DriverManager.registerDriver(new DriverShim(driver));
            driverReady = true;
        } catch (Exception e) {
            throw new SQLException("Неуспешно зареждане на H2 driver от lib/h2.jar", e);
        }
    }

    // DriverManager accepts drivers from current classloader via a shim wrapper.
    private static final class DriverShim implements Driver {
        private final Driver driver;

        private DriverShim(Driver driver) {
            this.driver = driver;
        }

        @Override
        public Connection connect(String url, Properties info) throws SQLException {
            return driver.connect(url, info);
        }

        @Override
        public boolean acceptsURL(String url) throws SQLException {
            return driver.acceptsURL(url);
        }

        @Override
        public DriverPropertyInfo[] getPropertyInfo(String url, Properties info) throws SQLException {
            return driver.getPropertyInfo(url, info);
        }

        @Override
        public int getMajorVersion() {
            return driver.getMajorVersion();
        }

        @Override
        public int getMinorVersion() {
            return driver.getMinorVersion();
        }

        @Override
        public boolean jdbcCompliant() {
            return driver.jdbcCompliant();
        }

        @Override
        public Logger getParentLogger() throws java.sql.SQLFeatureNotSupportedException {
            return driver.getParentLogger();
        }
    }
}

