package bg.restaurant.swing.db;

import java.nio.file.Path;
import java.sql.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.DriverPropertyInfo;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.Properties;
import java.util.logging.Logger;

public final class Db {
    private static volatile boolean driverReady = false;

    private Db() {}

    public static Connection connect() throws SQLException {
        ensureDriverLoaded();
        // File-based H2 DB stored in ./data/worktime (relative to project/run dir)
        String dbPath = Path.of("data", "worktime").toAbsolutePath().toString().replace("\\", "/");
        String url = "jdbc:h2:file:" + dbPath + ";AUTO_SERVER=TRUE;MODE=PostgreSQL";
        return DriverManager.getConnection(url, "sa", "");
    }

    public static void init() throws SQLException {
        try (Connection c = connect(); Statement s = c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS employee (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(200) NOT NULL UNIQUE" +
                    ")");

            s.execute("CREATE TABLE IF NOT EXISTS shift (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "employee_id BIGINT NOT NULL, " +
                    "start_time TIMESTAMP NOT NULL, " +
                    "end_time TIMESTAMP NULL, " +
                    "CONSTRAINT fk_shift_employee FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE" +
                    ")");

            s.execute("CREATE INDEX IF NOT EXISTS idx_shift_employee ON shift(employee_id)");
            s.execute("CREATE INDEX IF NOT EXISTS idx_shift_start ON shift(start_time)");

            s.execute("CREATE TABLE IF NOT EXISTS app_user (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "access_code VARCHAR(32) NOT NULL UNIQUE, " +
                    "is_admin BOOLEAN NOT NULL DEFAULT FALSE" +
                    ")");
            s.execute("ALTER TABLE app_user ADD COLUMN IF NOT EXISTS display_name VARCHAR(200)");
            s.execute("ALTER TABLE app_user ADD COLUMN IF NOT EXISTS employee_id BIGINT");

            s.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_app_user_code ON app_user(access_code)");

            // Ensure default admin user exists.
            try (PreparedStatement ps = c.prepareStatement(
                    "MERGE INTO app_user(access_code, is_admin, display_name, employee_id) KEY(access_code) VALUES (?, ?, ?, ?)")) {
                ps.setString(1, "9876");
                ps.setBoolean(2, true);
                ps.setString(3, "Админ");
                ps.setObject(4, null);
                ps.executeUpdate();
            }
        }
    }

    private static synchronized void ensureDriverLoaded() throws SQLException {
        if (driverReady) return;

        try {
            Class.forName("org.h2.Driver");
            driverReady = true;
            return;
        } catch (ClassNotFoundException ignored) {
            // fallback below
        }

        try {
            Path jarPath = Path.of("lib", "h2.jar").toAbsolutePath();
            if (!jarPath.toFile().exists()) {
                throw new SQLException("Липсва H2 библиотека: " + jarPath);
            }
            URL jarUrl = jarPath.toUri().toURL();
            URLClassLoader loader = new URLClassLoader(new URL[]{jarUrl}, Db.class.getClassLoader());
            Class<?> driverClass = Class.forName("org.h2.Driver", true, loader);
            Driver driver = (Driver) driverClass.getDeclaredConstructor().newInstance();
            DriverManager.registerDriver(new DriverShim(driver));
            driverReady = true;
        } catch (Exception e) {
            throw new SQLException("Неуспешно зареждане на H2 driver от lib/h2.jar", e);
        }
    }

    // DriverManager accepts drivers from current classloader via a shim wrapper.
    private static final class DriverShim implements Driver {
        private final Driver driver;

        private DriverShim(Driver driver) {
            this.driver = driver;
        }

        @Override
        public Connection connect(String url, Properties info) throws SQLException {
            return driver.connect(url, info);
        }

        @Override
        public boolean acceptsURL(String url) throws SQLException {
            return driver.acceptsURL(url);
        }

        @Override
        public DriverPropertyInfo[] getPropertyInfo(String url, Properties info) throws SQLException {
            return driver.getPropertyInfo(url, info);
        }

        @Override
        public int getMajorVersion() {
            return driver.getMajorVersion();
        }

        @Override
        public int getMinorVersion() {
            return driver.getMinorVersion();
        }

        @Override
        public boolean jdbcCompliant() {
            return driver.jdbcCompliant();
        }

        @Override
        public Logger getParentLogger() throws java.sql.SQLFeatureNotSupportedException {
            return driver.getParentLogger();
        }
    }
}

